name: rostelekom_main_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-10.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  lottie: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/prof1.png
    # - assets/animations/done.json
    - lib/assets/images/fon.jpg

