// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-cdE5zR1B4pV3A7MpramYyX2NCygtHCQ',
    appId: '1:436900197065:web:b6d87a700a4af32cd71318',
    messagingSenderId: '436900197065',
    projectId: 'rostelekom-a2a2e',
    authDomain: 'rostelekom-a2a2e.firebaseapp.com',
    storageBucket: 'rostelekom-a2a2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPZqS7tOeKzI0yOFwS-WN0ovBgHLQDwE',
    appId: '1:436900197065:android:fd11f80892d92176d71318',
    messagingSenderId: '436900197065',
    projectId: 'rostelekom-a2a2e',
    storageBucket: 'rostelekom-a2a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzkhdY69CU2qpbXOmPtGYLS_FMFWrAmgg',
    appId: '1:436900197065:ios:02d50c95d5ec5b73d71318',
    messagingSenderId: '436900197065',
    projectId: 'rostelekom-a2a2e',
    storageBucket: 'rostelekom-a2a2e.appspot.com',
    iosClientId: '436900197065-ujemd6pul6tpv4l9f574qvs01spienj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rostelekomMainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzkhdY69CU2qpbXOmPtGYLS_FMFWrAmgg',
    appId: '1:436900197065:ios:93b1cd200d6fbd4dd71318',
    messagingSenderId: '436900197065',
    projectId: 'rostelekom-a2a2e',
    storageBucket: 'rostelekom-a2a2e.appspot.com',
    iosClientId: '436900197065-l6r8jqndke5kr0ehanrv1l4j9p0i0lq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.rostelekomMainApp.RunnerTests',
  );
}
